version: "3"
services:
  prometheus_service:
    image: prom/prometheus
    container_name: prom_1
    ports:
      - 9090:9090
    volumes:
      - ./prometheus-data:/prometheus-data
    command: --config.file=/prometheus-data/prometheus.yml

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'